### ISSUE TITLE
flying multiple drones with web 

### ISSUE THREAD

**Issue by Ritesh1991** [AlexisTM/flyingros#4]
Hi if i want to fly multiple drone through this set up what and where should I start ? Can you guide me ?

**Comment by AlexisTM** [comment]
Hi there, flying multiple drones is much more complex (fleet management) than one. 

I would propose you FKIE_multimaster to run multiple interconnected ROS masters across the network and using the task system to actually control them. 

Never forget that you have a 6D flying object; Never put "blocking tasks" or else it will crash. You always need to send setpoints.

**Comment by AlexisTM** [comment]
@Ritesh1991 Any update?

**Comment by Ritesh1991** [comment]
yeh it's possible two way either using through reverse vpn client on drone which connect drone to cloud or server. other one is blockchain but 2 one is complicated now stage

**Comment by AlexisTM** [comment]
Easiest is VPN (zerotier/OpenVPN) + fkie_multimaster/rocon.
